// apps/web/src/components/header.tsx
import { ArrowRightIcon, BoxIcon } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";

export function Header() {
  return (
    <header className="p-4 flex justify-between items-center">
      <Link href="/" className="flex gap-2 items-center">
        <BoxIcon />
        ContainerMC
      </Link>
      <NavigationMenu>
        <NavigationMenuList>
          <NavigationMenuItem>
            <NavigationMenuTrigger>Products</NavigationMenuTrigger>
          </NavigationMenuItem>
          <NavigationMenuItem>
            <NavigationMenuTrigger>Solutions</NavigationMenuTrigger>
          </NavigationMenuItem>
          <NavigationMenuItem>
            <NavigationMenuTrigger>Resources</NavigationMenuTrigger>
          </NavigationMenuItem>
          <NavigationMenuItem>
            <NavigationMenuLink
              render={<Link href="/pricing" />}
              className={navigationMenuTriggerStyle()}
            >
              Pricing
            </NavigationMenuLink>
          </NavigationMenuItem>
        </NavigationMenuList>
      </NavigationMenu>
      <Button render={<Link href="/sign-in" />} nativeButton={false} size="lg">
        Get Started
        <ArrowRightIcon />
      </Button>
    </header>
  );
}

// src/lib/components/header.svelte
<script lang="ts">
  import { resolve } from "$app/paths";
  import ArrowUpRightIcon from "phosphor-svelte/lib/ArrowUpRightIcon";

  import { authClient } from "#lib/auth-client.ts";
  import { Button } from "#lib/components/ui/button/index.ts";
  import * as NavigationMenu from "#lib/components/ui/navigation-menu/index.ts";
  import { navigationMenuTriggerStyle } from "#lib/components/ui/navigation-menu/navigation-menu-trigger.svelte";

  const session = authClient.useSession();
</script>

<header class="flex items-center justify-between border-b p-4">
  <a href={resolve("/")}>ContainerMC</a>
  <NavigationMenu.Root>
    <NavigationMenu.List>
      <NavigationMenu.Item>
        <NavigationMenu.Trigger>Item One</NavigationMenu.Trigger>
        <NavigationMenu.Content>
          <NavigationMenu.Link>Link</NavigationMenu.Link>
        </NavigationMenu.Content>
      </NavigationMenu.Item>
      <NavigationMenu.Item>
        <NavigationMenu.Link>
          {#snippet child()}
            <a href={resolve("/pricing")} class={navigationMenuTriggerStyle()}>Pricing</a>
          {/snippet}
        </NavigationMenu.Link>
      </NavigationMenu.Item>
    </NavigationMenu.List>
  </NavigationMenu.Root>
  {#if $session.data}
    <Button href={resolve("/dashboard")}
      >Dashboard
      <ArrowUpRightIcon />
    </Button>
  {:else}
    <div class="flex gap-2">
      <Button href={resolve("/auth")}>Get Started</Button>
    </div>
  {/if}
</header>
