// src/routes/sign-in/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { resolve } from "$app/paths";
  import SiDiscord from "@icons-pack/svelte-simple-icons/icons/SiDiscord";
  import SiGithub from "@icons-pack/svelte-simple-icons/icons/SiGithub";
  import { createForm } from "@tanstack/svelte-form";
  import { z } from "zod";

  import { authClient } from "#lib/auth-client.ts";
  import { Button } from "#lib/components/ui/button/index.ts";
  import * as Card from "#lib/components/ui/card/index.ts";
  import * as Field from "#lib/components/ui/field/index.ts";
  import { Input } from "#lib/components/ui/input/index.ts";
  import * as Separator from "#lib/components/ui/separator/index.ts";

  const signInSchema = z.object({
    email: z.email("Enter a valid email address"),
    password: z.string().min(1, "Enter your password"),
  });

  let errorMessage = $state("");

  const form = createForm(() => ({
    defaultValues: { email: "", password: "" },
    validators: { onSubmit: signInSchema },
    onSubmit: async ({ value }) => {
      errorMessage = "";
      const { error } = await authClient.signIn.email({
        email: value.email,
        password: value.password,
      });

      if (error) {
        errorMessage = error.message ?? "Unable to sign in";
        return;
      }

      await goto("/");
    },
  }));
</script>

<svelte:head>
  <title>ContainerMC - Sign in</title>
</svelte:head>

<main class="flex min-h-screen items-center justify-center p-4">
  <Card.Root class="w-full max-w-sm">
    <Card.Header>
      <Card.Title>Sign in</Card.Title>
      <Card.Description>Enter your email and password to continue.</Card.Description>
    </Card.Header>
    <Card.Content>
      <div class="flex flex-col gap-2">
        <Button
          onclick={async () =>
            await authClient.signIn.social({
              provider: "discord",
              callbackURL: resolve("/dashboard"),
            })}
          type="button"
          variant="outline"
          class="w-full"
        >
          <SiDiscord />
          Continue with Discord
        </Button>
        <Button
          onclick={async () =>
            await authClient.signIn.social({
              provider: "github",
              callbackURL: resolve("/dashboard"),
            })}
          type="button"
          variant="outline"
          class="w-full"
        >
          <SiGithub />
          Continue with GitHub</Button
        >
      </div>
      <div class="text-muted-foreground my-4 flex items-center gap-2 text-xs">
        <Separator.Root class="flex-1" />
        <span>or</span>
        <Separator.Root class="flex-1" />
      </div>
      <form
        onsubmit={(event) => {
          event.preventDefault();
          form.handleSubmit();
        }}
        class="flex flex-col gap-4"
      >
        <form.Field name="email">
          {#snippet children(field)}
            <Field.Field data-invalid={field.state.meta.errors.length > 0}>
              <Field.Label for="sign-in-email">Email</Field.Label>
              <Input
                id="sign-in-email"
                type="email"
                autocomplete="email"
                value={field.state.value}
                onblur={field.handleBlur}
                oninput={(event) => field.handleChange(event.currentTarget.value)}
                aria-invalid={field.state.meta.errors.length > 0}
              />
              <Field.Error
                errors={field.state.meta.errors.filter(Boolean) as { message?: string }[]}
              />
            </Field.Field>
          {/snippet}
        </form.Field>

        <form.Field name="password">
          {#snippet children(field)}
            <Field.Field data-invalid={field.state.meta.errors.length > 0}>
              <Field.Label for="sign-in-password">Password</Field.Label>
              <Input
                id="sign-in-password"
                type="password"
                autocomplete="current-password"
                value={field.state.value}
                onblur={field.handleBlur}
                oninput={(event) => field.handleChange(event.currentTarget.value)}
                aria-invalid={field.state.meta.errors.length > 0}
              />
              <Field.Error
                errors={field.state.meta.errors.filter(Boolean) as { message?: string }[]}
              />
            </Field.Field>
          {/snippet}
        </form.Field>

        {#if errorMessage}<p class="text-destructive text-xs" role="alert">{errorMessage}</p>{/if}
        <Button
          type="submit"
          disabled={!form.state.canSubmit || form.state.isSubmitting}
          class="w-full">{form.state.isSubmitting ? "Signing in…" : "Sign in"}</Button
        >
      </form>
    </Card.Content>
    <Card.Footer class="text-muted-foreground justify-center gap-1">
      <span>Don’t have an account?</span>
      <Button variant="link" href="/sign-up">Sign up</Button>
    </Card.Footer>
  </Card.Root>
</main>

// apps/web/src/app/sign-in/page.tsx
"use client";

import { useForm } from "@tanstack/react-form";
import { BoxIcon } from "lucide-react";
import Link from "next/link";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/components/ui/input-otp";
import { Separator } from "@/components/ui/separator";
import { authClient } from "@/lib/auth-client";

const schema = z.object({
  email: z.email(),
});

export default function SignIn() {
  const form = useForm({
    defaultValues: {
      email: "",
    },
    validators: {
      onSubmit: schema,
      onChange: schema,
      onBlur: schema,
    },
    onSubmit: async ({ value }) => {
      const { data, error } = await authClient.emailOtp.sendVerificationOtp({
        email: value.email,
        type: "sign-in",
      });
    },
  });

  return (
    <div className="flex flex-col">
      <header className="p-4">
        <Link href="/" className="flex items-center gap-2">
          <BoxIcon />
          ContainerMC
        </Link>
      </header>
      <Card className="max-w-sm w-full mx-auto">
        <CardHeader>
          <CardTitle>Welcome to ContainerMC</CardTitle>
          <CardDescription>
            Sign in or create an account to get started
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-2">
            <Button
              onClick={async () =>
                await authClient.signIn.social({
                  provider: "discord",
                })
              }
              size="lg"
              variant="secondary"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                aria-hidden="true"
                role="img"
                width="64"
                height="64"
                viewBox="0 0 24 24"
              >
                <path
                  fill="currentColor"
                  d="m22 24l-5.25-5l.63 2H4.5A2.5 2.5 0 0 1 2 18.5v-15A2.5 2.5 0 0 1 4.5 1h15A2.5 2.5 0 0 1 22 3.5V24M12 6.8c-2.68 0-4.56 1.15-4.56 1.15c1.03-.92 2.83-1.45 2.83-1.45l-.17-.17c-1.69.03-3.22 1.2-3.22 1.2c-1.72 3.59-1.61 6.69-1.61 6.69c1.4 1.81 3.48 1.68 3.48 1.68l.71-.9c-1.25-.27-2.04-1.38-2.04-1.38S9.3 14.9 12 14.9s4.58-1.28 4.58-1.28s-.79 1.11-2.04 1.38l.71.9s2.08.13 3.48-1.68c0 0 .11-3.1-1.61-6.69c0 0-1.53-1.17-3.22-1.2l-.17.17s1.8.53 2.83 1.45c0 0-1.88-1.15-4.56-1.15m-2.07 3.79c.65 0 1.18.57 1.17 1.27c0 .69-.52 1.27-1.17 1.27c-.64 0-1.16-.58-1.16-1.27c0-.7.51-1.27 1.16-1.27m4.17 0c.65 0 1.17.57 1.17 1.27c0 .69-.52 1.27-1.17 1.27c-.64 0-1.16-.58-1.16-1.27c0-.7.51-1.27 1.16-1.27Z"
                ></path>
              </svg>
              Discord
            </Button>
            <Button
              onClick={async () =>
                await authClient.signIn.social({
                  provider: "github",
                })
              }
              size="lg"
              variant="secondary"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                aria-hidden="true"
                role="img"
                width="64"
                height="64"
                viewBox="0 0 24 24"
              >
                <path
                  fill="currentColor"
                  d="M12 2A10 10 0 0 0 2 12c0 4.42 2.87 8.17 6.84 9.5c.5.08.66-.23.66-.5v-1.69c-2.77.6-3.36-1.34-3.36-1.34c-.46-1.16-1.11-1.47-1.11-1.47c-.91-.62.07-.6.07-.6c1 .07 1.53 1.03 1.53 1.03c.87 1.52 2.34 1.07 2.91.83c.09-.65.35-1.09.63-1.34c-2.22-.25-4.55-1.11-4.55-4.92c0-1.11.38-2 1.03-2.71c-.1-.25-.45-1.29.1-2.64c0 0 .84-.27 2.75 1.02c.79-.22 1.65-.33 2.5-.33s1.71.11 2.5.33c1.91-1.29 2.75-1.02 2.75-1.02c.55 1.35.2 2.39.1 2.64c.65.71 1.03 1.6 1.03 2.71c0 3.82-2.34 4.66-4.57 4.91c.36.31.69.92.69 1.85V21c0 .27.16.59.67.5C19.14 20.16 22 16.42 22 12A10 10 0 0 0 12 2"
                ></path>
              </svg>
              GitHub
            </Button>
            <Button
              onClick={async () =>
                await authClient.signIn.social({
                  provider: "google",
                })
              }
              size="lg"
              variant="secondary"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                aria-hidden="true"
                role="img"
                width="64"
                height="64"
                viewBox="0 0 24 24"
              >
                <path
                  fill="currentColor"
                  d="M21.35 11.1h-9.17v2.73h6.51c-.33 3.81-3.5 5.44-6.5 5.44C8.36 19.27 5 16.25 5 12c0-4.1 3.2-7.27 7.2-7.27c3.09 0 4.9 1.97 4.9 1.97L19 4.72S16.56 2 12.1 2C6.42 2 2.03 6.8 2.03 12c0 5.05 4.13 10 10.22 10c5.35 0 9.25-3.67 9.25-9.09c0-1.15-.15-1.81-.15-1.81"
                ></path>
              </svg>
              Google
            </Button>
            <Button
              onClick={async () =>
                await authClient.signIn.social({
                  provider: "github",
                })
              }
              size="lg"
              variant="secondary"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                aria-hidden="true"
                role="img"
                width="64"
                height="64"
                viewBox="0 0 24 24"
              >
                <path
                  fill="currentColor"
                  d="M2 3h9v9H2zm9 19H2v-9h9zM21 3v9h-9V3zm0 19h-9v-9h9z"
                ></path>
              </svg>
              Microsoft
            </Button>
          </div>
          <div className="flex items-center gap-2">
            <Separator className="flex-1" />
            <p>or</p>
            <Separator className="flex-1" />
          </div>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              form.handleSubmit();
            }}
            className="space-y-4"
          >
            <FieldGroup>
              <form.Field name="email">
                {(field) => {
                  const isInvalid =
                    field.state.meta.isBlurred && !field.state.meta.isValid;
                  return (
                    <Field data-invalid={isInvalid}>
                      <FieldLabel htmlFor={field.name}>Your Email</FieldLabel>
                      <Input
                        aria-invalid={isInvalid}
                        autoComplete="email"
                        onBlur={field.handleBlur}
                        id={field.name}
                        name={field.name}
                        placeholder="you@example.com"
                        value={field.state.value}
                        onChange={(e) => field.handleChange(e.target.value)}
                      />
                      {isInvalid && (
                        <FieldError errors={field.state.meta.errors} />
                      )}
                    </Field>
                  );
                }}
              </form.Field>
            </FieldGroup>
            <form.Subscribe
              selector={(state) => ({
                canSubmit: state.canSubmit,
                isSubmitting: state.isSubmitting,
              })}
            >
              {({ canSubmit, isSubmitting }) => (
                <Button
                  disabled={!canSubmit || isSubmitting}
                  type="submit"
                  className="w-full"
                >
                  Continue with email
                </Button>
              )}
            </form.Subscribe>
          </form>
        </CardContent>
        <CardFooter>
          <p className="text-balance text-muted-foreground text-xs text-center">
            By continuing, you agree to our{" "}
            <Link href="/terms" className="underline underline-offset-4">
              Terms of Service
            </Link>{" "}
            and{" "}
            <Link href="/privacy" className="underline underline-offset-4">
              Privacy Policy
            </Link>
            .
          </p>
        </CardFooter>
      </Card>
    </div>
  );
}
